Chore/update spec
Psychedelic/DIP721 pull request #50
Opened 2022-03-10 19:40 UTC by MichaelMoriarty67

## Why?

Update spec.md to follow dip721 v2

## How?

Reviewed DIP721 v2 candid file.

## Tickets?

N / A

## Contribution checklist?

- [ ] The commit messages are detailed
- [ ] It does not break existing features (unless required)
- [ ] I have performed a self-review of my own code
- [ ] Documentation has been updated to reflect the changes
- [ ] Tests have been added or updated to reflect the changes
- [ ] All code formatting pass
- [ ] All lints pass
- [ ] All tests pass

## Security checklist?

- [ ] Injection has been prevented (parameterized queries, no eval or system calls)
- [ ] Sensitive data has been identified and is being protected properly

## Demo?

N / A

2022-03-14 19:58 UTC, ozwaldorf commented on spec.md
> -
We shouldn't remove these, maybe put them after the metadata

2022-03-15 12:02 UTC, heldrida requested changes
I find that this PR is a bit too long for what it claims to cover which I read and understand as "docs: v2 specification".

🙏 Ideally, let's keep PR meaningful so that's easier for everyone to contribute with feedback not just particular knowledge users, a none dev should be able to read the v2 specification, which might not understand the source code here.

The PR seems a bit too long, and there are a few things that I find should be looked at separately.

2022-03-15 12:02 UTC, punkbit commented on nft-v2/nft-v2.did
> +  custodians : opt vec principal;
Is there any particular reason we've opted to use "Custodians" instead of "Owners"?

```suggestion
  custodians : opt vec principal;
```

Considering that's hinted as "Owner" in the original EIP-721, we have places were the term is declared, such as the token metadata:

```rust
type TokenMetadata = record {
  owner : opt principal;
   ....
};
```

We also have methods named as

```
ownerOf
ownerTokenMetadata
...
```

Seems more consistent to use one or the other but not both, if we're planning to communicate clearly to a wider audience and be a bit more inclusive to keep "english easy" for none natives, a personal suggestion.

2022-03-15 12:02 UTC, punkbit commented on nft-v2/src/migration_example.rs
> +use super::*;
Would like to see the test for this, to confirm it's running and working as intended, as I won't be able to go through the whole code or implementation.

Also, unless I missed a separate PR that includes the migration example, I find that this PR is a bit too long for what it claims to cover which I read and understand as "docs: v2 specification".

Ideally, let's keep PR meaningful so that's easier for everyone to contribute with feedback not just particular knowledge users, a none dev should be able to read the v2 specification, which might not understand the source code here.

2022-03-15 12:09 UTC, scott-dn commented on nft-v2/nft-v2.did
> +  custodians : opt vec principal;
please refer to #52 as this PR is based on
this PR for docs related
---------------
`custodians` mean canister owner
`owner` mean NFT owner
previously they were both same and quite ambiguous hence `custodians` helps
inspire from here
https://github.com/dfinity/examples/blob/master/rust/dip721-nft-container/src/lib.rs

2022-03-15 13:33 UTC, scott-dn commented on nft-v2/src/migration_example.rs
> +use super::*;
The main purpose is to provider example that helps users understand how to migrate. 
They can change the logic as needed.
Beside, the `migration_exampler.rs` file is separated and doesn't have to be a part of DIP721

2022-03-15 13:45 UTC, heldrida commented on nft-v2/nft-v2.did
> +  custodians : opt vec principal;
Got it!

2022-03-15 16:03 UTC, heldrida approved these changes

2022-03-16 09:44 UTC, merged